services:  
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    hostname: jellyfin
    ports:
      - 8096:8096
    volumes:
      - ./jellyfin/config:/config
      - ./media/media:/data/media
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=002
      - TZ=${TZ:-Etc/UTC}
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped