version: "3.5"

networks:
  default:
    attachable: true
    name: "neko-rooms-net"

services:
  neko-rooms:
    container_name: neko-rooms
    image: "m1k1o/neko-rooms:latest"
    networks:
      - neko-rooms-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/docker/neko-rooms/data:/data"
    env_file:
      - stack.env
    ports:
      - 8081:8080 # Many services use port 8080, make sure to update
    restart: "unless-stopped"

# Don't forget to include an .env file
