services:
  all-in-one:
    init: true
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    ports:
      #- 80:80
      - 8090:8080
      #- 8443:8443
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: nextcloud/all-in-one:latest
    environment:
      NEXTCLOUD_DATADIR: ./data/nextcloud
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 0.0.0.0
      NEXTCLOUD_ENABLE_DRI_DEVICE: true
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
