version: "3.8"
services:
    cadvisor:
        container_name: cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        ports:
            - 8080:8080
        container_name: cadvisor
        privileged: true
        devices:
            - /dev/kmsg
        image: gcr.io/cadvisor/cadvisor:v0.36.0
