---
services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    network_mode: 'bridge'
    ports:
      - 5055:5055
    volumes:
      - /home/docker/jellyseerr/config:/app/config
    environment:
      - LOG_LEVEL=debug
    env_file:
      - stack.env
    restart: unless-stopped

# Don't forget to include an .env file