---
services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    network_mode: 'bridge'
    ports:
      - 5055:5055
    volumes:
      - /home/docker/jellyseerr/config:/app/config
    environment:
      TZ: ${TZ:-Etc/UTC}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
    restart: unless-stopped

# Don't forget to include an .env file