---
services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    network_mode: 'bridge'
    ports:
      - 5055:5055
    volumes:
      - /home/docker/jellyseerr/config:/app/config
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
    restart: unless-stopped
