services:
  uptime-kuma:
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - ./data/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    network_mode: bridge