---
networks:
  default:
    attachable: true
    name: "jellyfin"

services:
  jellyfin:
    container_name: jellyfin
    image: flywithpeace/jellyfin-sso:latest
    hostname: jellyfin
    ports:
      - 8096:8096
    volumes:
      - /home/docker/jellyfin/config:/config
      - media:/data
    environment:
      TZ: ${TZ:-Etc/UTC}
      NVIDIA_VISIBLE_DEVICES: all # nvenc support
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    runtime: nvidia # nvenc support
    restart: unless-stopped
  
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - 5055:5055
    volumes:
      - /home/docker/jellyseerr/config:/app/config
    environment:
      TZ: ${TZ:-Etc/UTC}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
    restart: unless-stopped

volumes:
  media:
    external: True # Using volumes because media is shared on NFS

# Don't forget to include an .env file