---
services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    network_mode: 'bridge'
    ports:
      - 8096:8096
    volumes:
      - /home/docker/jellyfin/config:/config
      - media:/data
    environment:
      TZ: ${TZ:-Etc/UTC}
      NVIDIA_VISIBLE_DEVICES: all # nvenc support
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    runtime: nvidia # nvenc support
    restart: unless-stopped

volumes:
  media:
    external: True # Using volumes because media is shared on NFS

# Don't forget to include an .env file