---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: 'bridge'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8082:80/tcp" # Many services uses port 80, make sure to update
    volumes:
      - ./data/pihole/etc-pihole:/etc/pihole
      - ./data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    environment:
      TZ: ${TZ:-Etc/UTC}
      WEBPASSWORD: ${WEBPASSWORD:?You need to set a admin password}
    restart: unless-stopped

# Don't forget to include an .env file
