version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8082:80/tcp"
    volumes:
      - '/home/docker/pihole/etc-pihole:/etc/pihole'
      - '/home/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
