---
services:
  code-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:latest
    network_mode: 'bridge'
    ports:
      - 8443:8443
    volumes:
      - /home/docker/code-server/config:/config
    environment:
      TZ: ${TZ:-Etc/UTC}
      SUDO_PASSWORD: ${SUDO_PASSWORD:?sudo password required if you want to install packages}
    restart: unless-stopped

# Don't forget to include an .env file