---
services:
  code-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:latest
    network_mode: 'bridge'
    ports:
      - 8443:8443
    volumes:
      - /home/docker/code-server/config:/config
    env_file:
      - stack.env
    restart: unless-stopped

# Don't forget to include an .env file