---
services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    network_mode: 'bridge'
    ports:
      - 9696:9696
    volumes:
      - /home/docker/prowlarr/config:/config
    env_file:
      - stack.env
    restart: unless-stopped

# Don't forget to include an .env file
