---
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    network_mode: 'bridge'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ:-Etc/UTC}
    restart: unless-stopped

# Don't forget to include an .env file
