---
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    network_mode: 'bridge'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped