services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112
      - 58846:58846
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:?Define your VPN provider}
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY:?Provide the private key}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES:?Provide the address}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:?Define your country}
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=002 # Do not change
      - TZ=${TZ:-Etc/UTC}
      - DELUGE_LOGLEVEL=${DELUGE_LOGLEVEL:-error}
    volumes:
      - ./cofig:/config
      - ./media/torrents:/data/torrents
    restart: unless-stopped
    network_mode: service:gluetun
